### ISSUE TITLE
Support for Pose Estimation?

### ISSUE THREAD

**Issue by jimmybuffi** [roboflow/inference#11]
Thank you so much for this valuable contribution! Curious if there are plans to add support for pose estimation / key point detection in the near future?

**Comment by yeldarby** [comment]
Yes, definitely! Which model would you like to see added?

We've thought about adding [Mediapipe's Pose Estimation model](https://developers.google.com/mediapipe/solutions/vision/pose_landmarker#:~:text=The%20MediaPipe%20Pose%20Landmarker%20task,with%20single%20images%20or%20video.) and [YOLOv8's pose model](https://docs.ultralytics.com/tasks/pose/). Would one of those work for your use-case?

**Comment by jimmybuffi** [comment]
Awesome! Thanks for the response!

Both of these models are awesome for different reasons. Mediapipe I think has a more permissive license but doesn't seem to be as accurate... YOLO has the more restrictive license but also seems to be more accurate...

The one I really like for its permissive license and accuracy is ViTPose:
https://github.com/ViTAE-Transformer/ViTPose

**Comment by yeldarby** [comment]
We're working on facial landmarks & gaze detection in PR #20; pose estimation is on the short list. We'll look into those models as part of our planning. Thanks @jimmybuffi!

Once we add the first one and define the output format it should be pretty easy to add additional models as well so folks can try them all & see which one works best for their use-case.

**Comment by PawelPeczek-Roboflow** [comment]
As part of already shipped releases we introduced keypoints detection.
