### ISSUE TITLE
Video Inference

### ISSUE THREAD

**Issue by loretoparisi** [roboflow/inference#14]
Hello, Roboflow is presented with an amazing detection of soccer players in [this](https://x.com/skalskip92/status/1692258273838215423?s=46&t=LFe0jyu2TCnvXZNEvnb71g) tweet, is it possible to provide an example of video inference then?

Thank you in advance!

**Comment by SkalskiP** [comment]
Hi, @loretoparisi 👋🏻! 

Take a look at this repository: https://github.com/roboflow/inference-client, and this YouTube tutorial: https://youtu.be/at-yuwIMiN4.

**Comment by yeldarby** [comment]
Fixed in #81
