### ISSUE TITLE
Does Inference not work with Windows?

### ISSUE THREAD

**Issue by medhanshrath-t** [roboflow/inference#144]
### Search before asking

- [X] I have searched the Inference [issues](https://github.com/roboflow/inference/issues) and found no similar feature requests.

### Question

I am trying to run inference on Windows to do inferencing with YOLO v8 with my GPU. When I try` inference server start` I get the following error: `TypeError: Invalid type for device_requests param: expected list but found <class 'tuple'>`.  

This works: `docker run --network=host --gpus=all roboflow/roboflow-inference-server-gpu:latest` but then the server does not accept any requests: 
`ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=9001): Max retries exceeded with url: /doctr/ocr?api_key=St4BLhrH2dLkV8EQuXG4 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001C585F67150>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))`

**Comment by prasadvineetv** [comment]
I have the same issue. Were you able to resolve?

**Comment by yeldarby** [comment]
we have customers using `inference` with GPU access on Windows.

Are you running in WSL? Have you been able to verify your NVIDIA drivers and CUDA setup with the NVIDIA test container with:
```sh
sudo docker run --rm --runtime=nvidia --gpus all ubuntu nvidia-smi
```

**Comment by medhanshrath-t** [comment]
I got the following error:

```
docker: Error response from daemon: unknown or invalid runtime name: nvidia.
See 'docker run --help'.
```

Do you have any idea how I could fix it?

**Comment by femacklin** [comment]
I had the same issue...binding the image to a specific port worked for me.
`docker run -p 9001:9001 -it --gpus=all --rm roboflow/roboflow-inference-server-gpu:latest`

**Comment by grzegorz-roboflow** [comment]
I have windows10 on my laptop and followed the following:

0. updated my system
1. Installed [wsl2](https://learn.microsoft.com/en-us/windows/wsl/install)
2. installed [docker for windows](https://docs.docker.com/desktop/install/windows-install/)
3. installed [nvidia container toolkit](https://www.server-world.info/en/note?os=Ubuntu_20.04&p=nvidia&f=2) (probably not required)
4. restarted my machine
5. `docker run --rm --runtime=nvidia --gpus all ubuntu nvidia-smi` works

Then tried following:
```bash
docker run --network=host --gpus=all roboflow/roboflow-inference-server-gpu:latest
```

I can see no errors

**Comment by grzegorz-roboflow** [comment]
@medhanshrath-t, I will close this issue since with information provided there is not much more help I can provide, but please feel free to reopen if you have further questions.
