### ISSUE TITLE
Video and webcam inference 

### ISSUE THREAD

**Issue by lakshanthad** [roboflow/inference#18]
Hello,

I want to know how to use the open-source inference server to inference on video inputs and webcam inputs.

I saw there is a repo for video inference here:
https://github.com/roboflow/inference-client

However, that repo is only suited if you are running the inference server via Docker.

So how can we do video and webcam inputs after installing the inference server via pip?

**Comment by paulguerrie** [comment]
Hi @lakshanthad ,

You have a couple options here:

1. Start an http server using the pip package.
2. Use the models directly

For option 1, see the config script we use in our docker images: https://github.com/roboflow/inference/blob/main/docker/config/cpu_http.py 
and see the dockerfile itself for how we use uvicorn to serve the http api: https://github.com/roboflow/inference/blob/5b22ec56a3537deb2d8fe1d90b482ecc0c3d91df/docker/dockerfiles/Dockerfile.onnx.cpu#L53C2-L53C3

For option 2, see the pip section of our quickstart in the readme: https://github.com/roboflow/inference/tree/main#-quickstart

Either option plus some of the stream reading code from https://github.com/roboflow/inference-client should work for video inference without the need for docker.

**Comment by lakshanthad** [comment]
Thank you for the details answer. I will check and feedback here.

**Comment by reedajohns** [comment]
Hi @lakshanthad,

We've added a blog post outlining how to do this with a webcam! Check it out here: https://blog.roboflow.com/inference-python/

**Comment by yeldarby** [comment]
Fixed in #81
