### ISSUE TITLE
Poetry-installing `inference` with `roboflow` takes 26 - 38 minutes.

### ISSUE THREAD

**Issue by LinasKo** [roboflow/inference#289]
### Search before asking

- [X] I have searched the Inference [issues](https://github.com/roboflow/inference/issues) and found no similar bug report.

### Bug

Starting with an empty project, `poetry`, python 3.10 environment, I ran:
```bash
poetry init -n
poetry shell
poetry add notebook
poetry add roboflow
poetry add inference
```

This was enough to make dependency resolution last 2319.0s.

Subsequently run of `poetry add tqdm` took 213.2s, following which I got "No dependencies to install or update".

Adding `ipywidgets` took another 220.5s.

<br/>

Whether it's an issue with `inference`, `poetry` or `roboflow` or their dependencies, the end result is a very miserable dev experience.

### Environment

- Inference 0.9.14
- Roboflow 1.1.20

- Ubuntu 22.04.4 LTS
- Alienware 15 r3

- Python 3.10.12
- Pip 23.3.2
- Poetry 1.3.1

### Minimal Reproducible Example

```bash
poetry init -n
poetry shell
poetry add roboflow
poetry add inference
# Took 1578.6s
```

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by LinasKo** [comment]
To rule out the obvious, here's my internet speed.
![image](https://github.com/roboflow/inference/assets/6500785/f39c69fe-4cb7-4dfe-bf27-bf008859f12c)

Just in case, I'll rerun the aforementioned poetry setup.

Update: yep, still resolving very slowly.

**Comment by PawelPeczek-Roboflow** [comment]
Thanks for the report - we will take a look.

**Comment by hvaria** [comment]
Upon personal testing, both manual venv creation and Poetry-initiated environments showed no extended dependency resolution times, suggesting the issue is system specific. Optimizing system resources and upgrading to SSDs can significantly improve Poetry's performance, ensuring a smoother development workflow.

**Comment by LinasKo** [comment]
Oh, only on my machine? That's a relief.

Will add a small comment if I ever find out why. In the mean time, happy to treat this as resolved.

**Comment by PawelPeczek-Roboflow** [comment]
I believer that we have issue with upper-bound definitions of requirements (eg: `package<=XXX`) which makes it hard in some cases to install in specific environments where other packages exists, especially in such tough management system as poetry is. I know it must be quite problematic for @LinasKo, we will try to make things better, but we do also have another requirements conflicts raised internally that we need to resolve. All boils down to support of multiple targets (including edge devices) - and it's likely we will need some time to resolve that iussue.

**Comment by LinasKo** [comment]
Looking into this now

**Comment by LinasKo** [comment]
Noting down the findings so far.

This happens even without `roboflow`. Simply running `poetry add inference` on a newly created `poetry` project causes this for me - I even had installation run for an hour without completion. Tested on my machine (poetry 1.3), and a new $12 Digital Ocean Ubuntu 22.04 droplet (poetry 1.1).

Found another issue where poetry completely fails to install `inference` when using `python 3.11.x`, with x >= 1. Seems like python env specifications `<=3.11` are treated as `<=3.11.0` by `poetry`.

---

Doing some dependency analysis on the first problem it's clear that `poetry` repeatedly checks hundreds upon hundreds of both `awscli` and `botocore` until finding a match. Docs in both `poetry` and `pip` say such backtracking is inherent to how Python handles packages, and it's only solvable by narrowing down the search space, like Pawel mentioned in prior comment.

However, to my surprise, removing `skypilot` (which brings `awscli`) from the dependencies eliminates the `awscli` check, but does not make the installation any faster. Very curious. Perhaps it is a hardware compatibility issue after all?..

I'll do a check with a few folks in the company, see how widespread this is. `pip` install works, so perhaps this is not widespread.

**Comment by grzegorz-roboflow** [comment]
Hi @LinasKo ,

I'm not using poetry on my day-to-day work but I tried following and noticed the time required is lower than what you report:

```bash
python3.8 -m venv venv
source venv/bin/activate
pip install poetry
poetry init -n
# I had to change `python` versions to ">=3.8,<3.11" in `pyproject.toml`
sed -i.bak -e 's/^python[ ]*=.*/python = ">=3.8,<3.11"/g' pyproject.toml
poetry add inference
# Resolving dependencies... (63.5s)
# once dependencies are resolved installation was pretty much instant
poetry add notebook
# Resolving dependencies... (13.0s)
# installation instant
poetry add roboflow
# Resolving dependencies... (6.9s)
# installation instant
```

I also tried to install them in the same order as you
```bash
python3.8 -m venv venv
source venv/bin/activate
pip install poetry
poetry init -n
# I had to change `python` versions to ">=3.8,<3.11" in `pyproject.toml`
sed -i.bak -e 's/^python[ ]*=.*/python = ">=3.8,<3.11"/g' pyproject.toml
poetry add notebook
# Resolving dependencies... (3.6s)
# installation instant
poetry add roboflow
# Resolving dependencies... (1.7s)
# installation instant
poetry add inference
# Resolving dependencies... (23.4s)
# installation instant
poetry add tqdm
# Resolving dependencies... (2.4s)
# installation instant (it actually downgraded scipy in my case)
```

It seems I cannot reproduce the problem..

**Comment by LinasKo** [comment]
It's awesome to see this being tested!

In fact, I followed your steps and it was much faster. (`poetry 1.8.2`)

However, I can still reproduce the issue if I use `poetry` globally installed on my system (`1.8.1`)
The installation hasn't completed in the last 10 minutes.

I'll verify with `venv` and older version just in case...

**Comment by ethanknights** [comment]
Just to document, this isn't poetry-specific. I've encountered the same issue with downloading exhaustive versions of `awscli` and `botocore` with a plain `pip install inference`:

```
Collecting botocore>=1.29.10
  Downloading botocore-1.31.81-py3-none-any.whl (11.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.3/11.3 MB 869.4 kB/s eta 0:00:00
Collecting awscli>=1.27.10
  Downloading awscli-1.29.80-py3-none-any.whl (4.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.3/4.3 MB 464.1 kB/s eta 0:00:00
Collecting botocore>=1.29.10
  Downloading botocore-1.31.80-py3-none-any.whl (11.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.3/11.3 MB 980.9 kB/s eta 0:00:00
Collecting awscli>=1.27.10
  Downloading awscli-1.29.79-py3-none-any.whl (4.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.3/4.3 MB 832.2 kB/s eta 0:00:00
Collecting botocore>=1.29.10
  Downloading botocore-1.31.79-py3-none-any.whl (11.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.3/11.3 MB 923.3 kB/s eta 0:00:00
Collecting awscli>=1.27.10
  Downloading awscli-1.29.78-py3-none-any.whl (4.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.3/4.3 MB 502.7 kB/s eta 0:00:00
Collecting botocore>=1.29.10
  Downloading botocore-1.31.78-py3-none-any.whl (11.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.3/11.3 MB 895.8 kB/s eta 0:00:00
```
