### ISSUE TITLE
CLI Should Work Without Docker

### ISSUE THREAD

**Issue by yeldarby** [roboflow/inference#312]
### Search before asking

- [X] I have searched the Inference [issues](https://github.com/roboflow/inference/issues) and found no similar bug report.

### Bug

I installed `inference-gpu` on a fresh VM (inside a docker container). I want to use the CLI to run the benchmark. But it's complaining that the docker daemon is not running.

```
inference_cli.lib.exceptions.DockerConnectionErrorException: Error connecting to Docker daemon. Is docker installed and running? See https://www.docker.com/get-started/ for installation instructions.
```

I understand I'd need that for commands like `inference server start` but I shouldn't need it to do other things with the CLI.

### Environment

```
root@C.10017133:/$ pip freeze | grep inference
inference-cli==0.9.15
inference-gpu==0.9.15
inference-sdk==0.9.15
root@C.10017133:/$ 
```

`pytorch/pytorch:2.2.0-cuda12.1-cudnn8-devel` docker with after running `pip install inference-gpu`

<img width="729" alt="image" src="https://github.com/roboflow/inference/assets/870796/7d4cc3cc-9327-46a7-9b1f-33c4034aae9a">

### Minimal Reproducible Example

```
pip install inference-gpu
inference
```

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by PawelPeczek-Roboflow** [comment]
ok, found an issue - that's due to unused imports left in one module. That will be a quick fix

**Comment by PawelPeczek-Roboflow** [comment]
Introduced change: https://github.com/roboflow/inference/pull/317
