### ISSUE TITLE
Inference on video is extremely slow

### ISSUE THREAD

**Issue by tomershukhman** [roboflow/inference#324]
Hi,
Ran the code as metioned in the official [docs] (https://inference.roboflow.com/quickstart/run_model_on_rtsp_webcam/#installation)
But the output seems to be in a very slow frame rate.
any advice?
```python
# Import the InferencePipeline object
from inference import InferencePipeline
# Import the built in render_boxes sink for visualizing results
from inference.core.interfaces.stream.sinks import render_boxes

# initialize a pipeline object
pipeline = InferencePipeline.init(
    model_id="rock-paper-scissors-sxsw/11", # Roboflow model to use
    video_reference=0, # Path to video, device id (int, usually 0 for built in webcams), or RTSP stream url
    on_prediction=render_boxes, # Function to run after each prediction
)
pipeline.start()
pipeline.join()
```

**Comment by yeldarby** [comment]
What type of machine (CPU, GPU) are you running on? And which version of `inference` did you pip install?

Could you try running `inference benchmark python-package-speed -m "rock-paper-scissors-sxsw/11"` and post the output?

**Comment by tomershukhman** [comment]
Running on macbook m1 pro.
<img width="1399" alt="image" src="https://github.com/roboflow/inference/assets/30184884/a73bf6de-be34-483d-b98b-058b549606c9">
I am uanble to attach a video recording since github has a very small size limit, but when i run the code (as posted before) the video seems to have a very slow frame rate.

**Comment by yeldarby** [comment]
23 frames per second on CPU isn’t bad, but you should be able to get a bit more.

In order to get hardware acceleration on an M1 you need to install the Metal Performance Shader runtime. It’s experimental but I’ve seen it be quite a bit faster than the default CPU provider.

Try doing `pip install onnxruntime-silicon` then `export  ONNXRUNTIME_EXECUTION_PROVIDERS =“[CoreMLExecutionProvider]”` and re-run the benchmark.

**Comment by tomershukhman** [comment]
Done
First I justed noticed I accidentally pasted a wrong code sinppet so adding it here (and edited in the orignal post.)
```python
from inference import InferencePipeline
from inference.core.interfaces.stream.sinks import render_boxes

pipeline = InferencePipeline.init(
    model_id="yolov8x-1280",
    video_reference="https://media.roboflow.com/inference/people-walking.mp4",
    on_prediction=render_boxes
)   

pipeline.start()
pipeline.join()
```

<img width="1423" alt="image" src="https://github.com/roboflow/inference/assets/30184884/4bfee730-47fd-4506-bfe0-4aaa7610f097">

 How do I do that in my python code to see if now the video seems at normal speed?

Another question (sorry for being such a rocki)
Does `on_prediction=render_boxes` means that we don't render anything for images without detaction? if so that witht explain the slow frame rate since many are simply not displayed

My goal is to see an mp4

**Comment by tomershukhman** [comment]
I justed noticed I accidentally pasted a wrong code sinppet so adding it here.
```python
from inference import InferencePipeline
from inference.core.interfaces.camera.entities import VideoFrame

# import opencv to display our annotated images
import cv2
# import supervision to help visualize our predictions
import supervision as sv

# create a simple box annotator to use in our custom sink
annotator = sv.BoxAnnotator()

def my_custom_sink(predictions: dict, video_frame: VideoFrame):
    # get the text labels for each prediction
    labels = [p["class"] for p in predictions["predictions"]]
    # load our predictions into the Supervision Detections api
    detections = sv.Detections.from_inference(predictions)
    # annotate the frame using our supervision annotator, the video_frame, the predictions (as supervision Detections), and the prediction labels
    image = annotator.annotate(
        scene=video_frame.image.copy(), detections=detections, labels=labels
    )
    # display the annotated image
    cv2.imshow("Predictions", image)
    cv2.waitKey(1)

pipeline = InferencePipeline.init(
    model_id="yolov8x-1280",
    video_reference="https://storage.googleapis.com/com-roboflow-marketing/inference/people-walking.mp4",
    on_prediction=my_custom_sink,
)

pipeline.start()
pipeline.join()
```


```
export  ONNXRUNTIME_EXECUTION_PROVIDERS="[CoreMLExecutionProvider]" 
inference benchmark python-package-speed -m "yolov8x-1280"  
```
and the results are
<img width="1375" alt="image" src="https://github.com/roboflow/inference/assets/30184884/45878d09-40e9-4218-8219-155e9bcacdfb">
(still has not finished bull all number are below)

As mentioned before I just copy pasting the example from the offical docs
The snippet I copied is the last in "[Define Custom Prediction Logic](https://inference.roboflow.com/quickstart/run_model_on_rtsp_webcam/#define-custom-prediction-logic)"

**Comment by PawelPeczek-Roboflow** [comment]
ok, so the case is now a bit more clear.
`yolov8x-1280` is the largest YOLOv8 model, additionally chosen version of the model uses 1280px image as an input - making it ~1.5s to get the inference result. This result matches with our benchmarks.
My question now would be - do you need real-time processing or detailed prediction results?
If the former - using such a big model on your machine would not be feasible - so I suggest trying smaller models 
If the latter - I suggest using more powerful machine (possibly with GPU)

**Comment by tomershukhman** [comment]
Real time processing.
Which model would you suggest?

BTW really sorry for the contusion I caused.

**Comment by PawelPeczek-Roboflow** [comment]
no problem - we are here to help.
I suggest testing different models staring from smallest ones to decide which is the fastest model you can use that keeps the accuracy at satisfactory level.

Here you can find yolov8 models you can use (ordered from smalles to largest): https://inference.roboflow.com/quickstart/aliases/

**Comment by tomershukhman** [comment]
Awesome, yeah that was it - using `model_id="yolov8n-640"` does run smoothly.
How can I make sure it utilizes the mac m1 hardware?

**Comment by PawelPeczek-Roboflow** [comment]
you mean the `CoreMLExecutionProvider`?

**Comment by PawelPeczek-Roboflow** [comment]
if you take a look here: 
![image](https://github.com/roboflow/inference/assets/146137186/bed03006-3582-4a5e-9eaf-263ebf36de5e)
there are logs indicating that to happen

**Comment by tomershukhman** [comment]
I meant when running the code inference with python

**Comment by yeldarby** [comment]
That CLI command is using the python package so if it's utilizing `onnxruntime-silicon` your python code will be as well. The key is to ensure that 1) the m1 accelerated onnxruntime is installed and 2) the environment variable setting the preferred runtime to use is set in the context where your code is running.

Note that the MPS (metal performance shader) can't be passed through to Docker ([yet?](https://github.com/pytorch/pytorch/issues/81224)) so you'll only get accelerated performance when running directly on the host machine.

**Comment by tomershukhman** [comment]
Awesome, really appriciate all of your guys help

**Comment by PawelPeczek-Roboflow** [comment]
Pleasure is all ours. I do assume that solves the question. If not - do not hesitate to ask.

**Comment by p0we7** [comment]
@tomershukhman 
Hi, I'm trying to use my M2 Max for inference and I'm only able to use the cpu for labor right now. I installed this issue's method but it doesn't seem to work.
And my computer doesn't have the command yolo inference, what other packages do I need to install?

**Comment by PawelPeczek-Roboflow** [comment]
Hi there,
`yolo inference` is not a command, I guess that `yolo` displayed is probably directory name of the person submitting the screenshot

**Comment by PawelPeczek-Roboflow** [comment]
`I installed this issue's method but it doesn't seem to work` - didn't fps value increase or increased by a value not satisfying for you?

**Comment by p0we7** [comment]
@PawelPeczek-Roboflow Okay, but I don't yet have a valid way for me to confirm that CoreML acceleration is being used.

**Comment by PawelPeczek-Roboflow** [comment]
Ok, so I guess u don't see outputs similar to:
![image](https://github.com/roboflow/inference/assets/146137186/d91e0233-02e6-41d5-851a-105abcb4b9e8)

I assume u executed this:
```bash
pip install onnxruntime-silicon 
export  ONNXRUNTIME_EXECUTION_PROVIDERS="[CoreMLExecutionProvider]"   # please make sure u changed ” from original response into "
````

**Comment by PawelPeczek-Roboflow** [comment]
ok, @p0we7 - that's good actually - the warning says: You have now those providers:
`CoreMLExecutionProvider, CPUExecutionProvider`,
you have selected `CUDAExecutionProvider, OpenVINOExecutionProvider`

that would probably default into `CPUExecutionProvider`

Please:
```bash
export  ONNXRUNTIME_EXECUTION_PROVIDERS="[CoreMLExecutionProvider]"
```

**Comment by p0we7** [comment]
@PawelPeczek-Roboflow 

Thanks for the tip, I rechecked my environment variables and I realized that I didn't succeed in adding the environment variable values, I ignored export.
But when I successfully enabled acceleration, I noticed that the speed didn't improve, is there any other handy improvement?

<img width="1077" alt="image" src="https://github.com/roboflow/inference/assets/8407573/aabab570-f9d8-40a2-bb24-6d1fd4aa3696">

**Comment by PawelPeczek-Roboflow** [comment]
It is strange to see CoreML being slower than CPU for the model, yet the values you reach are in range of what I expected for this model under the mentioned specs. What performance would be matching your expectations?

**Comment by p0we7** [comment]
Because I'm trying to record a video of the prediction process, and when both prediction and recording start at the same time, it gets slow.

**Comment by PawelPeczek-Roboflow** [comment]
ok, but it seems to be resource bottleneck issue - how you record? Maybe that is possible to be achieved differently

**Comment by p0we7** [comment]
> you could record results of model inference into file and then do a voice-over?

What should I do, are there examples in the official documentation that present this?

**Comment by PawelPeczek-Roboflow** [comment]
novice questions are fine, no worries - glad that u have started the journey with us. Let me know if I can help with anything else
