### ISSUE TITLE
How can I use custom weights with Yolo-World Model?

### ISSUE THREAD

**Issue by Dragosjosan** [roboflow/inference#340]
### Search before asking

- [X] I have searched the Inference [issues](https://github.com/roboflow/inference/issues) and found no similar feature requests.

### Question

The model performance of the Yolo World Hugging Face model (https://huggingface.co/spaces/stevengrove/YOLO-World)  is better for my purpose than the standard inference one "yolo_world/v2-x" for example.

Because my lack of domain knowledge regarding this topics I can't make the HF model work on my Mac (not an M processor) so I would like to be able to use the model weights with the abstraction from the Roboflow inference library.

Is there any way to use the author's provided weights together with the inference library?

From the author's instruction on how to run the model on an image one needs the configuration file and the weights: https://github.com/AILab-CVC/YOLO-World

The conf file I want to use and the weights are available here: 
https://huggingface.co/spaces/stevengrove/YOLO-World/blob/main/configs/pretrain/yolo_world_l_t2i_bn_2e-4_100e_4x8gpus_obj365v1_goldg_train_lvis_minival.py
https://huggingface.co/spaces/stevengrove/YOLO-World/blob/main/yolow-v8_l_clipv2_frozen_t2iv2_bn_o365_goldg_pretrain.pth

Thank you in advance

**Comment by LLH-Harward** [comment]
I have the same question. Is there any solution available? Thank you.

**Comment by grzegorz-roboflow** [comment]
Currently there is no straight forward way of achieving this (you will need to use our internals) however in the future the situation may improve as we are considering feature requests like this (taking under account other work we have in our pipeline).

At the moment you can save your model in onnx format and place it in Roboflow cache directory (default location is "/tmp/cache", can be controlled by "MODEL_CACHE_DIR" environmental variable)

If you run any model from our examples you can see how does the required file structure look like and what should be included in each file.

**Comment by Dragosjosan** [comment]
@grzegorz-roboflow ok, thank you for the update.

**Comment by grzegorz-roboflow** [comment]
Thanks @Dragosjosan , I will close this issue but please feel free to reopen if you have further questions.
