### ISSUE TITLE
Duplicate Inference with `client.infer_on_stream()` on Windows

### ISSUE THREAD

**Issue by NickHerrig** [roboflow/inference#349]
### Search before asking

- [X] I have searched the Inference [issues](https://github.com/roboflow/inference/issues) and found no similar bug report.

## The Issue
I'm currently experiencing unexpected behavior when running inference on a directory of images using inference_sdk. When I run the method `infer_on_stream()` the context manager loops through the files twice on Windows 10 resulting in double the inferences. 

Below is a code snippet to recreate the issue. 

```python
from inference_sdk import InferenceHTTPClient

image_path="C:\\Users\\nick\\Desktop\\bug\\images"

client = InferenceHTTPClient(
    api_url="https://detect.roboflow.com/",
    api_key="" # redacted
)

for file_path, image, prediction in client.infer_on_stream(input_uri=image_path, model_id="coco/3"):
    print(file_path)
```

Image Dir Contents:

![image](https://github.com/roboflow/inference/assets/33797354/80e3806e-39cf-49e7-b527-b9e6f19d38e9)

Console Output:

![image](https://github.com/roboflow/inference/assets/33797354/4a2c585c-344f-4c3c-832f-e88c9beea918)

### Environment

- inference-sdk 0.9.20
- Python 3.10.11
- Windows 10

### Minimal Reproducible Example

```
from inference_sdk import InferenceHTTPClient

image_path="C:\\Users\\nick\\Desktop\\bug\\images"

client = InferenceHTTPClient(
    api_url="https://detect.roboflow.com/",
    api_key="" # redacted
)

for file_path, image, prediction in client.infer_on_stream(input_uri=image_path, model_id="coco/3"):
    print(file_path)
```

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by PawelPeczek-Roboflow** [comment]
sorted out on branch: https://github.com/roboflow/inference/pull/343
will be released soon
