### ISSUE TITLE
If I try to make an inference with a local RTSP, I still need to run API_KEY and server, right?

### ISSUE THREAD

**Issue by YoungjaeDev** [roboflow/inference#383]
### Search before asking

- [X] I have searched the Inference [issues](https://github.com/roboflow/inference/issues) and found no similar feature requests.

### Question

Due to the roboflow inference structure, even if I simply use a local RTSP_STREAM, do I still need to start the server and enter the API_KEY? Or is there another way?

**Comment by grzegorz-roboflow** [comment]
Hi @YoungjaeDev, you do not need to provide API_KEY if you are using foundational models. Consider below example:

```
source /path/to/venv/where/inference/is/installed/bin/activate
inference server start
inference infer --input /Users/grzegorzklimaszewski/Downloads/chess-pieces/20240423_101935.jpg --model_id yolov8m-seg-640
# yields {'time': 0.24999908400002369, 'image': {'width': 3000, 'height': 4000}, 'predictions': []}
```

**Comment by grzegorz-roboflow** [comment]
Hi @YoungjaeDev, I will go ahead and close this issue. Please reopen if you would like to share more context.
