### ISSUE TITLE
Need to skip Yoloact inst-seg tests for the parallel GPU inference server

### ISSUE THREAD

**Issue by bigbitbus** [roboflow/inference#384]
### Search before asking

- [X] I have searched the Inference [issues](https://github.com/roboflow/inference/issues) and found no similar bug report.

### Bug

When running the tests on Nvidia T4 via GH actions, such errors are encountered: https://github.com/roboflow/inference/actions/runs/8992522142

This is because the parallel GPU inference docker does not support Yoloact Inst Seg.

This code fixes the issue by skipping yoloact tests: 

https://github.com/roboflow/inference/blob/2aa0127f5a6a59b7a641a2182875fedb1696ebce/tests/inference/integration_tests/batch_regression_test.py#L202

https://github.com/roboflow/inference/blob/2aa0127f5a6a59b7a641a2182875fedb1696ebce/tests/inference/integration_tests/regression_test.py#L409

After this, the GH action passes (example link below):
https://github.com/roboflow/inference/actions/runs/9023206470

PR to make the test change: https://github.com/roboflow/inference/pull/379

### Environment

Nvidia GPU container

### Minimal Reproducible Example

https://github.com/roboflow/inference/actions/runs/8992522142

### Are you willing to submit a PR?
Yes, already submitted #379 
- [ ] Yes I'd like to help by submitting a PR!

**Comment by bigbitbus** [comment]
@PawelPeczek-Roboflow fixing the GPU test

**Comment by PawelPeczek-Roboflow** [comment]
👍
