### ISSUE TITLE
Add Python 3.12 support 

### ISSUE THREAD

**Issue by PawelPeczek-Roboflow** [roboflow/inference#433]
### Search before asking

- [X] I have searched the Inference [issues](https://github.com/roboflow/inference/issues) and found no similar feature requests.

### Description

Python 3.12 is not supported now due to incompatibility of dependencies, mainly `onnxruntime~=1.15.x`.
There is a chance to set `onnxruntime<=1.17.1` - please evaluate on all supported platforms.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by Milor123** [comment]
No have support still? we need it.

**Comment by PawelPeczek-Roboflow** [comment]
No, unfortunately we still don't support python 3.12.
