### ISSUE TITLE
FPS Drop

### ISSUE THREAD

**Issue by codin-son** [roboflow/inference#460]
### Search before asking

- [X] I have searched the Inference [issues](https://github.com/roboflow/inference/issues) and found no similar feature requests.

### Question

im trying to run code that provided in inferencepipeline documentation

`from inference import InferencePipeline
from inference.core.interfaces.stream.sinks import render_boxes

pipeline = InferencePipeline.init(
    model_id="yolov8n-640", 
    video_reference=0,
    on_prediction=render_boxes, 
)

pipeline.start()
pipeline.join()`

the thing is, when i run the code, the fps drop until 1 and half fps. this also happen when im using my rtsp camera and webcam. it also happen when i run on my other pc. im using latest inference version library

**Comment by PawelPeczek-Roboflow** [comment]
Hi there,

Could you please provide more information on the problem? Does drop happens immediately or it is faster at the beginning?
What is the hardware you run the code?

**Comment by gmijo47** [comment]
Facing same problem from RTSP 
#484
https://github.com/roboflow/inference/discussions/484

**Comment by grzegorz-roboflow** [comment]
Hi @codin-son , it seems the problem was investigated in #484 and some suggestions were provided there so I'll go ahead and close this issue, but please feel free to reopen if your original issue is not solved.
