### ISSUE TITLE
Deleting image tags

### ISSUE THREAD

**Issue by talhaahussain** [roboflow/inference#506]
### Search before asking

- [X] I have searched the Inference [issues](https://github.com/roboflow/inference/issues) and found no similar feature requests.

### Description

Presently, RoboFlow provides tags as a way to organize datasets. Presently, we can create tags for images in a dataset, as well as add images under a tag. However, there is no support for deleting these tags.

### Use case

It would be very useful to prevent redundant or incorrect tags from building up.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by SolomonLake** [comment]
Thank you @talhaahussain . We have this feature on our roadmap. I will update here when it is added.

**Comment by grzegorz-roboflow** [comment]
Hi @talhaahussain , I will close this bug report, please feel to update it with further information once feature is added as reported by @SolomonLake .
