### ISSUE TITLE
How can I get predicted label and the coordinates of the detection bbox ?

### ISSUE THREAD

**Issue by yuyoujiang** [roboflow/inference#51]
### Search before asking

- [X] I have searched the Inference [issues](https://github.com/roboflow/inference/issues) and found no similar feature requests.

### Question

I reference [this blog](https://blog.roboflow.com/clip-jetson-orin/) to build and run the docker image in Jetson. Then I reference [this repo](https://github.com/roboflow/roboflow-api-snippets/blob/main/Python/webcam/infer-simple.py) to implement webcam inference. It can run successfully. 
But `requests.post()` function simply returns an image that draws the bboxes. How can I get predicted label and the coordinates of the detection bbox ?

**Comment by paulguerrie** [comment]
Hi @yuyoujiang !  If you remove the `&format=image` [from the request](https://github.com/roboflow/roboflow-api-snippets/blob/50bed6096ace5a82b59f72bb3f816b5748d05746/Python/webcam/infer-simple.py#L26), the response will be a json response that includes the bounding boxes and classes.

**Comment by yuyoujiang** [comment]
Thanks to your help, my problem has been solved!
