### ISSUE TITLE
Bug: Abnormal Confidence Scores in YOLO-World Inference Due to New Version Bug

### ISSUE THREAD

**Issue by pg56714** [roboflow/inference#529]
### Search before asking

- [X] I have searched the Inference [issues](https://github.com/roboflow/inference/issues) and found no similar bug report.

### Bug

Sample
https://github.com/pg56714/YoloWorldDemo

person wearing green clothes
![1224276_original](https://github.com/user-attachments/assets/bf49cbcc-9eea-44cb-ba1d-2e0652035224)

inference-gpu[yolo-world]==0.13.0 and inference[yolo-world]==0.13.0  Confidence Threshold 0.2 is not ok
Confidence Threshold 0.15
![image](https://github.com/user-attachments/assets/8e60611f-1c47-4883-9b5f-86f6b960d167)

**Confidence Threshold 0.2** --> It should be the same as version 0.2 of 0.9.15.
![image](https://github.com/user-attachments/assets/14d6f772-3648-4543-a571-ac0b00edc5f1)

inference-gpu[yolo-world]==0.9.15 and inference[yolo-world]==0.9.15 is ok
Confidence Threshold 0.15
![image](https://github.com/user-attachments/assets/b715815d-22da-4ff8-868a-d3e56bee04a8)

Confidence Threshold 0.2
![image](https://github.com/user-attachments/assets/681f0ce6-f154-42e6-a255-d78336d70b5c)

### Environment

python=3.10
inference==0.13.0 and inference==0.14.0

### Minimal Reproducible Example

Same as above

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by PawelPeczek-Roboflow** [comment]
Hello there :)

So, to sum up - it seems like:
* the same model version
* the same confidence
behaves differently under different `inference` package version. Were all examples that provided tested in the same moment?

**Comment by PawelPeczek-Roboflow** [comment]
I remember one switch in YoloWorld weights after initial appearance in `inference` - if image depicting version `0.9.15` is old - maybe that's the case

**Comment by pg56714** [comment]
@PawelPeczek-Roboflow 

Hello, thank you for your reply.
- the same model version
- the same confidence
behaves differently under different inference package versions. Were all examples that provided tested at the same moment?

--> Yes, all tests were conducted on the same day.
- I first tested version 0.9.15, then reinstalled a new environment, and encountered this issue.
- Conversely, the same issue occurred when I first installed a new environment and then tested version 0.9.15.

I remember one switch in YoloWorld weights after initial appearance in inference - if the image depicting version 0.9.15 is old - maybe that's the case.

--> I apologize, but that's not the reason. Firstly, 0.9.15 used the old model, yolo_world/l, but the new version has this issue with all new models.

The old version only supports:
YOLO_WORLD_MODEL = YOLOWorld(model_id="yolo_world/l")

The new version supports:
YOLO_WORLD_MODEL = YOLOWorld(model_id="yolo_world/s")
YOLO_WORLD_MODEL = YOLOWorld(model_id="yolo_world/m")
YOLO_WORLD_MODEL = YOLOWorld(model_id="yolo_world/l")
YOLO_WORLD_MODEL = YOLOWorld(model_id="yolo_world/x")

YOLO_WORLD_MODEL = YOLOWorld(model_id="yolo_world/v2-s")
YOLO_WORLD_MODEL = YOLOWorld(model_id="yolo_world/v2-m")
YOLO_WORLD_MODEL = YOLOWorld(model_id="yolo_world/v2-l")
YOLO_WORLD_MODEL = YOLOWorld(model_id="yolo_world/v2-x")

However, using the YoloWorld code directly from their GitHub does not result in this problem, regardless of whether it is with the new model or the old model.

**Comment by pg56714** [comment]
Using the scenario described above:
1. With the new versions and the image provided, inputting "person wearing green clothes," none of the models could detect objects meeting the confidence threshold:
   - YOLO_WORLD_MODEL = YOLOWorld(model_id="yolo_world/s")
   - YOLO_WORLD_MODEL = YOLOWorld(model_id="yolo_world/m")
   - YOLO_WORLD_MODEL = YOLOWorld(model_id="yolo_world/l")
   - YOLO_WORLD_MODEL = YOLOWorld(model_id="yolo_world/x")
   - YOLO_WORLD_MODEL = YOLOWorld(model_id="yolo_world/v2-s")
   - YOLO_WORLD_MODEL = YOLOWorld(model_id="yolo_world/v2-m")
   - YOLO_WORLD_MODEL = YOLOWorld(model_id="yolo_world/v2-l")
   - YOLO_WORLD_MODEL = YOLOWorld(model_id="yolo_world/v2-x")

2. In version 0.9.15 with the same image, inputting "person wearing green clothes," the model could correctly detect objects meeting the confidence threshold:
   - YOLO_WORLD_MODEL = YOLOWorld(model_id="yolo_world/l")

**Comment by pg56714** [comment]
You can try it in my repository at https://github.com/pg56714/YoloWorldDemo. Thank.

**Comment by pg56714** [comment]
YOLO_WORLD_MODEL = YOLOWorld(model_id="yolo_world/l")

![1721104611969](https://github.com/user-attachments/assets/012c3d70-1929-4261-b821-2ca74177290c)
inference-gpu[yolo-world]==0.13.0 and inference[yolo-world]==0.13.0  Confidence Threshold 0.2 is not ok
**Confidence Threshold 0.2** --> It should be the same as version 0.2 of 0.9.15.
![image](https://github.com/user-attachments/assets/14d6f772-3648-4543-a571-ac0b00edc5f1)

**Comment by pg56714** [comment]
YOLO_WORLD_MODEL = YOLOWorld(model_id="yolo_world/v2-l")
![image](https://github.com/user-attachments/assets/48b12323-e06f-46d6-b0f0-8d70c384bc81)

![image](https://github.com/user-attachments/assets/9d9de908-ddff-4e9b-9c81-ca79d5472867)


![image](https://github.com/user-attachments/assets/c02b1921-39fa-4ed1-86b1-4d60ca4279d3)

**Comment by pg56714** [comment]
@PawelPeczek-Roboflow When only two objects remain in the final situation, if the confidence score condition is met by only one object, a bug occurs.

**Comment by PawelPeczek-Roboflow** [comment]
ok, thanks for details - will take a look

**Comment by PawelPeczek-Roboflow** [comment]
ok, found out where the problem is - we have faulty `squeeze()` in NMS function only revealing bug for singular detection prior to NMS. I expect that to be problematic for other models also - we'll see.
`np_conf_mask = (np_image_pred[:, 4] >= conf_thresh).squeeze()`

**Comment by PawelPeczek-Roboflow** [comment]
and after 0.9.15 we added post-processing with NMS to yolo-world - which explains why old version is not affected

**Comment by PawelPeczek-Roboflow** [comment]
created bug-fix PR: https://github.com/roboflow/inference/pull/535
we need to run all our tests to make sure we are not breaking anything else with this bug-fix, so probably will take a while until release - but thanks for the report - that was a very nasty bug!

**Comment by pg56714** [comment]
Thank you for the fix. However, I would like to wait until the new version has been officially deployed and tested before closing this issue. Could you please inform me which version will include this fix and the expected release date?

Thank you very much for your assistance.

**Comment by grzegorz-roboflow** [comment]
Hi @pg56714 , we are about to release inference v.0.15.0

**Comment by pg56714** [comment]
OK. Thank.

**Comment by pg56714** [comment]
@PawelPeczek-Roboflow @grzegorz-roboflow 

new bug #539

**Comment by grzegorz-roboflow** [comment]
@pg56714 thank you for reporting the other bug! Was the original problem reported in this report resolved?

**Comment by pg56714** [comment]
I thought there was an issue, but I will give it a try now, thank you. I'll use an older version of gradio first, as the new version has conflicts, which has been noted in #539 .

**Comment by pg56714** [comment]
Done.
