### ISSUE TITLE
Compatiblity issue with latest onnxruntime

### ISSUE THREAD

**Issue by pandayummy** [roboflow/inference#532]
### Search before asking

- [X] I have searched the Inference [issues](https://github.com/roboflow/inference/issues) and found no similar feature requests.

### Description

inference 0.14.1 requires onnxruntime<=1.15.1, but you have onnxruntime 1.18.1 which is incompatible.
inference 0.14.1 requires typer==0.9.0, but you have typer 0.12.3 which is incompatible.

![image](https://github.com/user-attachments/assets/8f22db91-f8d1-4dbe-8e6d-fe7b333e6a0c)

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by PawelPeczek-Roboflow** [comment]
Hello there :)
Thanks for raising the problem.
I believe releasing pin on type would be easy, not sure with onnxruntime, as that is fundamental dependency in our stack. Is that not possible for you to use older onnxruntime?

**Comment by PawelPeczek-Roboflow** [comment]
also - I do not fully understand 
"inference 0.14.1 requires onnxruntime<=1.15.1, **but you have** onnxruntime 1.18.1 which is incompatible."
where do we have onnxruntime 1.18.1?

**Comment by kawaii2020** [comment]
I have onnxruntime 1.18.1 installed. I'm asking if you could upgrade the code to make it compatible with onnxruntime 1.18.1...

**Comment by patjones** [comment]
FWIW I currently can't downgrade onnxruntime to meet the requirement of inference
```
pip3 install --force-reinstall onnxruntime==1.15.1
ERROR: Could not find a version that satisfies the requirement onnxruntime==1.15.1 (from versions: 1.17.0, 1.17.1, 1.17.3, 1.18.0, 1.18.1)
ERROR: No matching distribution found for onnxruntime==1.15.1
```

**Comment by kawaii2020** [comment]
![image](https://github.com/user-attachments/assets/cd26f762-0026-4a10-a39b-7f88de27d8e3)

**Comment by PawelPeczek-Roboflow** [comment]
This is fundamental change that would need to be very carefully tested, as may potentially break compatibility with Roboflow platform or the devices we support. Nevertheless, it would be good idea to try - yet probably it will take some time before we could make that happen.

**Comment by grzegorz-roboflow** [comment]
We now have `onnxruntime>=1.15.1,<1.20.0` in our requirements
