### ISSUE TITLE
Bug: Abnormal Installation of inference-gpu[yolo-world] and inference[yolo-world]

### ISSUE THREAD

**Issue by pg56714** [roboflow/inference#539]
### Search before asking

- [X] I have searched the Inference [issues](https://github.com/roboflow/inference/issues) and found no similar bug report.

### Bug
Version 0.15.0 cannot be installed successfully, while version 0.14.0 works fine.

gradio
inference-gpu[yolo-world] or  inference[yolo-world]
supervision

conda create -n yoloworlddemo python=3.10 -y
conda activate yoloworlddemo
pip install -r requirements.txt
![image](https://github.com/user-attachments/assets/0c79d917-2795-457f-892c-46540d4c1f0d)
![image](https://github.com/user-attachments/assets/7d9871ed-45c5-4ce1-8b46-ae4b5e9e83e0)

![image](https://github.com/user-attachments/assets/c6d9d99f-30aa-42e2-8afe-ca52d071fe16)
![image](https://github.com/user-attachments/assets/d7aa6d83-ad37-4774-976c-c61a2f4b1d17)
![image](https://github.com/user-attachments/assets/b84e86db-39f5-4691-aae1-2ee521b23c67)
![image](https://github.com/user-attachments/assets/0f366b5e-743b-42c2-a19f-83d9a0fd7b97)

Infinite loop

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by grzegorz-roboflow** [comment]
Hi, thank you for filling in the bug report!

I was able to install `inference-gpu` through pip and did not end up with infinite loop, I was issuing simple `pip install inference-gpu`.

I'm trying to reproduce your scenario - you seem to be installing through `requirements.txt` - I guess this is your project requirements file? Can you share it?

Thanks again!

**Comment by pg56714** [comment]
is pip install inference-gpu[yolo-world]
https://github.com/pg56714/YoloWorldDemo

**Comment by grzegorz-roboflow** [comment]
In linked `requirements.txt` I see `inference[yolo-world]==0.9.15` - did you mean `inference-gpu[yolo-world]==0.15.0`?

I was able to install corrected version of your `requirements.txt` on my Linux where I have GPU available, with `inference-gpu`, and the process completed with success:

```bash
mkdir roboflow_testing
cd roboflow_testing
cat > requirements.txt << EOF
gradio==4.19.2
inference-gpu[yolo-world]==0.15.0
supervision
EOF

docker run -it --rm -v $(pwd)/requirements.txt:/requirements.txt --entrypoint /bin/bash python:3.10 -c "pip install -r /requirements.txt"

```

**Comment by pg56714** [comment]
Yes, I will install inference-gpu[yolo-world]==0.15.0 and then give it a try. Thank you! My environment is Windows 10.

**Comment by pg56714** [comment]
Could you try this:
gradio
inference-gpu[yolo-world]]
supervision

My computer can handle:
gradio==4.19.2
inference-gpu[yolo-world]==0.15.0
supervision

But it cannot handle:
gradio
inference-gpu[yolo-world]]
supervision

**Comment by pg56714** [comment]
@grzegorz-roboflow 
Here's the issue:
gradio==4.19.2 is okay.

It seems there is a conflict with the new version of inference-gpu[yolo-world]:
gradio is not okay.

**Comment by grzegorz-roboflow** [comment]
I could observe `pip` having problem with version resolution of dependencies when there is no version bound on gradio and when it's installed before `inference-gpu`. However below worked fine:

```bash
mkdir roboflow_testing_2
cd roboflow_testing_2
cat > requirements.txt << EOF
inference-gpu[yolo-world]
gradio
supervision
EOF

docker run -it --rm -v $(pwd)/requirements.txt:/requirements.txt --entrypoint /bin/bash python:3.10 -c "pip install -r /requirements.txt"

```

**Comment by pg56714** [comment]
OK, thank you for the suggestion. Installing pip install inference-gpu[yolo-world] was successful. Initially, I thought there was an installation anomaly with the new version, but it appears there is a conflict with gradio. It seems the issue might indeed be with gradio; it's still not working correctly on my end.
