### ISSUE TITLE
Failed to build zxing-cpp

### ISSUE THREAD

**Issue by maxvaneck** [roboflow/inference#545]
### Search before asking

- [X] I have searched the Inference [issues](https://github.com/roboflow/inference/issues) and found no similar bug report.

### Bug

greetings,

i am trying to install inference on my jetson nano using pip(3) install inference . which fails with the error
Failed to build zxing-cpp

even when manually downloading the wheel file and just using pip3 install inference.whl

inference 0.15.1 
os latest quickstart image 
device nvidia jetson nano 

python 3.6.0 ?

### Environment

inference 0.15.1 
os latest quickstart image 
device nvidia jetson nano 

python 3.6.0 ?

### Minimal Reproducible Example

pip3 install inference

### Additional

the same happens on a community ubuntu 20.04 based image 

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by grzegorz-roboflow** [comment]
Hi @maxvaneck , can you post full error returned by pip when you attempt to install inference? Thanks!

**Comment by maxvaneck** [comment]
well you asked,


[log.txt](https://github.com/user-attachments/files/16333921/log.txt)

**Comment by grzegorz-roboflow** [comment]
Thanks for sharing the log. I see all packages are downloaded without error, and then at the bottom of the log pip issued this:

```
Downloading zipp-3.19.2-py3-none-any.whl (9.0 kB)
Building wheels for collected packages: zxing-cpp
  Building wheel for zxing-cpp (pyproject.toml): started
  Building wheel for zxing-cpp (pyproject.toml): finished with status 'error'
Failed to build zxing-cpp
```

Was there more information logged into stderr?

**Comment by maxvaneck** [comment]
I'll get back to you tomorrow. I'm done for today

**Comment by maxvaneck** [comment]
google tells me that stderr  also logs to the terminal which ive piped to log.txt so you should have both stderr and stdout

thx for the response 
Max

**Comment by grzegorz-roboflow** [comment]
Hi, I asked about stderr because information in the log does not pinpoint the reason of failure. It seems all packages had been downloaded and installed, these are relevant parts from the log file:

```
Collecting inference
  Downloading inference-0.15.1-py3-none-any.whl.metadata (14 kB)
(...)
(collecting and downloading inference dependencies)
(...)
Building wheels for collected packages: zxing-cpp
  Building wheel for zxing-cpp (pyproject.toml): started
  Building wheel for zxing-cpp (pyproject.toml): finished with status 'error'
Failed to build zxing-cpp
```

There seem to be no error related to inference reported within this log file.

Additionally it's worth highlighting that [we are not supporting python 3.6 since it reached end of life end of 2021](https://devguide.python.org/versions/)

**Comment by maxvaneck** [comment]
damn nvidia and their ubuntu 18.04 image which is also eol since  2023 . disregarding the jetson nano i get the sage error on ubuntu 24.04 desktop  x86_64 but not on windows 10  x86_64

**Comment by maxvaneck** [comment]
all of it related to zxing-cpp so maybe i should report the issues there

**Comment by grzegorz-roboflow** [comment]
Are there more logs available suggesting the build fails because of inference?

**Comment by maxvaneck** [comment]
no, it mainly seems to be zxing-cpp

**Comment by grzegorz-roboflow** [comment]
Thank you @maxvaneck , in such case I will close this issue but please feel free to reopen in case you have any more information.
