### ISSUE TITLE
no module named distutils

### ISSUE THREAD

**Issue by maxvaneck** [roboflow/inference#561]
### Search before asking

- [X] I have searched the Inference [issues](https://github.com/roboflow/inference/issues) and found no similar bug report.

### Bug

i tried to install inference on a fresh virtual environment using  both the built in package manager from pycharm and  simply pip3 install inference both gave me the error  "no module named distutils " attached is the full log 
[errorlog.txt](https://github.com/user-attachments/files/16493844/errorlog.txt)

### Environment

version:
inference 0.15.2 
hardware:
  x86 based desktop
OS: 
 ubuntu 24.04
python version:
3.12.3

### Minimal Reproducible Example

create a new virtal environment on ubunntu 14.04 
run pip3 install inference 

### Additional

after googling this seems to be an issue with python 3.12 removing distutils. in which case maybe this will help someone else running into the same problem. so this is not technically a bug but  maybe something to work around
https://peps.python.org/pep-0632/

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by iurisilvio** [comment]
See #433.

Inference doesn't support Python 3.12 yet because of their dependencies.

**Comment by maxvaneck** [comment]
i confirmed this using  ubuntu 22.04 using python  3.10.12 this works just fine

**Comment by iurisilvio** [comment]
Thanks! Closing this issue in favor of #433.
