### ISSUE TITLE
Inference directly on the image in the form of `np.ndarray` without the need to save it to hard drive

### ISSUE THREAD

**Issue by SkalskiP** [roboflow/inference#6]
Inference now takes the path to the image rather than the image itself. This makes video file processing highly suboptimal and creates a bottleneck.

```python
import requests

url = f"http://localhost:9001/{DATASET_ID}/{VERSION_ID}"

params = {
    "api_key": ROBOFLOW_API_KEY,
    "confidence": 0.5,
    "image": IMAGE_URL,
}

res = requests.post(url, params=params)
print(res.json())
```

It would be great if inference took `np.ndarray` directly. Example below is just pseudo-code.

```python
import requests
import supervision as sv

url = f"http://localhost:9001/{DATASET_ID}/{VERSION_ID}"

for frame in sv.get_video_frames_generator(source_path=VIDEO_PATH):

    params = {
        "api_key": ROBOFLOW_API_KEY,
        "confidence": 0.5,
        "image": frame,
    }
    
    res = requests.post(url, params=params)
    print(res.json())
```

🙋🏻 I would love to work on the implementation of this feature.

**Comment by yeldarby** [comment]
Nice, I'd love to see this also!

**Comment by paulguerrie** [comment]
Hey @SkalskiP ! For the HTTP interface, we do have a way to provide a numpy array:

```
import pickle
import requests
import supervision as sv

url = f"http://localhost:9001/{DATASET_ID}/{VERSION_ID}"

for frame in sv.get_video_frames_generator(source_path=VIDEO_PATH):

    params = {
        "api_key": ROBOFLOW_API_KEY,
        "confidence": 0.5,
        "image_type":"numpy"
    }
    
    res = requests.post(url, params=params, data=pickle.dumps(frame))
    print(res.json())
```

**Comment by SkalskiP** [comment]
Yeah. Now I would pivot this topic and focus on using `inference`, not as a server. And being able to pass `np.array` directly without pickling.

**Comment by paulguerrie** [comment]
Yup! 100% agree that we should do this. On our roadmap is to refactor the model APIs so that they are really easy and comfortable to use as a stand alone model (while also making development easy for various server interfaces like the http interface).

**Comment by SkalskiP** [comment]
How can I help? :)

**Comment by paulguerrie** [comment]
Added as of `0.8.0`
