### ISSUE TITLE
Clarification needed on coexistence of 'inference' and 'inference-gpu' packages

### ISSUE THREAD

**Issue by YoungjaeDev** [roboflow/inference#665]
### Search before asking

- [X] I have searched the Inference [issues](https://github.com/roboflow/inference/issues) and found no similar feature requests.

### Question

hello,

I currently have both 'inference' and 'inference-gpu' packages installed in my environment
```bash
inference 0.19.0
inference-gpu 0.19.0
```

I have two questions regarding this:

1. what is the specific role of the 'inference-gpu' package, and how does it differ from the 'inference' package?

2. Is it okay to have these two packages installed at the same time, or will it cause any problems like conflicts or performance degradation?

Thank you.

**Comment by yeldarby** [comment]
They're the same except for their dependencies. inference-gpu just pulls in the onnxruntime-gpu package instead of cpu only. 

I don't think there should be any problem having both if the versions are the same though I'm not 100% sure.
