### ISSUE TITLE
Run InferencePipeline with multiple models

### ISSUE THREAD

**Issue by ardhanapw** [roboflow/inference#669]
### Search before asking

- [X] I have searched the Inference [issues](https://github.com/roboflow/inference/issues) and found no similar feature requests.

### Question

Are there any ways to initialize InferencePipeline with multiple models? I'm planning to use three models, with the utilization as follows:

1. The first model is used to infer an object, returning the bounding box result of the object
2. the second model is used to detect part of the object based on the object's bounding box, returning bbox of the object's part
3. Utilizing the OCR model to read text written on the part

I tried InferencePipeline.init_with_workflow and the Supervision library, but the FPS dropped drastically and annotation results won't appear.

**Comment by PawelPeczek-Roboflow** [comment]
hi there,

Glad you managed to find Workflows and attempted to use it.
Could you share more details (preferably the workflow u created) then we could discuss about performance

**Comment by ardhanapw** [comment]
This is the workflow sequentially:
1. Input Image
2. The first model inferred input image to detect vehicles in the image
3. Bounding box result from the first model is then inferred by the second model to detect license plate
4. Detected license plate then read with OCR model

**Comment by ardhanapw** [comment]
The inputted image is coming from RTSP source

**Comment by PawelPeczek-Roboflow** [comment]
yeah, so you may potentially run multiple OCRs for each frame - OCR models we support are slower compared to detectors -  and this explain why you see slow-down

**Comment by ardhanapw** [comment]
Thanks for your help! I found a solution by limiting the model to just infer in even frames

**Comment by PawelPeczek-Roboflow** [comment]
👍 good idea
