### ISSUE TITLE
Batch Inference

### ISSUE THREAD

**Issue by Zizico2** [roboflow/inference#67]
### Search before asking

- [X] I have searched the Inference [issues](https://github.com/roboflow/inference/issues) and found no similar feature requests.

### Question

Is batch inference possible? For models that support it? I am currently using Triton Server directly, which supports arrays of inputs, but I'd like to try to use Inference Server, which seems to be a level of abstraction higher (specially once you support custom, non Roboflow weights). But I got significant performance improvements from infering in batches (yolov8) vs infering an image at a time.

**Comment by yeldarby** [comment]
It depends on the model but yes, if we support it on a given model you can pass an array of inputs.
