### ISSUE TITLE
Yolov9 bad results

### ISSUE THREAD

**Issue by alperemir** [roboflow/inference#736]
Hello, as you suggested, I balanced the classes and performed the training again and I share the results as below. In the tests I have done, the new model results become worse when gloves and glasses are added. How can I solve this problem?

![image (16)](https://github.com/user-attachments/assets/7632fd84-c486-42a3-86a9-5ed0a44ffd4d)

![classbalanced](https://github.com/user-attachments/assets/6e93578e-fa60-4aa5-a558-e6ab33a6a072)
-old model
![deneme20](https://github.com/user-attachments/assets/b6e8e3dc-52c6-4ef8-8584-47f530930c05)
-new model
![portrait-man-with-safety-equipment-side-view-carrying-ladder-1024x683 (1)](https://github.com/user-attachments/assets/4ee6b8cc-8f92-4342-8363-66dba20129d4)

dataset link: https://universe.roboflow.com/yavuzhan-zom9x/construction-site-safety-hvfor
Thanks for your support.

**Comment by PawelPeczek-Roboflow** [comment]
Hello, this seems to be the problem with model, we do not heave the context - your message suggest that you were given some instructions from Roboflow - could you specify where? Maybe you could follow up with that specific person

**Comment by grzegorz-roboflow** [comment]
I'm going to close this issue since there was no feedback provided. Please feel free to reopen if you still face this problem and gathered some more context to help us pinpoint the issue.
