### ISSUE TITLE
Is it compatible with newer versions of onnxruntime?

### ISSUE THREAD

**Issue by petercham** [roboflow/inference#757]
### Search before asking

- [X] I have searched the Inference [issues](https://github.com/roboflow/inference/issues) and found no similar feature requests.

### Question

Python Ver.3.11.8 (tags/v3.11.8:db85d51, Feb 6 2024, 22:03:32) [MSC v.1937 64 bit (AMD64)]
CUDA Ver.12.1
Torch Ver.2.3.1+cu121
cuDNN Ver. 8907
ONNXRuntime Ver.1.18.1

Now the environments themselves are compatible with each other, but not with inference 0.24. Currently only 1.15.1 is supported.

**Comment by grzegorz-roboflow** [comment]
Hi @petercham , we recently [updated our ONNX dependencies](https://github.com/roboflow/inference/pull/753), we are now running on ONNX runtime 0.19

**Comment by PawelPeczek-Roboflow** [comment]
will be released next Friday most likely

**Comment by yeldarby** [comment]
This is released [as of 0.25](https://github.com/roboflow/inference/releases/tag/v0.25).
