### ISSUE TITLE
Installing v0.28.0 is missing some files

### ISSUE THREAD

**Issue by RossLote** [roboflow/inference#834]
### Search before asking

- [X] I have searched the Inference [issues](https://github.com/roboflow/inference/issues) and found no similar bug report.

### Bug

For some reason, when I install v0.28 it is missing the `model_monitoring_inference_aggregator` directory. the result is the following:

```
from inference.core.workflows.core_steps.loader import (
  File "/Users/ross.lote/Projects/personal/robo-workflow/.venv/lib/python3.11/site-packages/inference/core/workflows/core_steps/loader.py", line 233, in <module>
    from inference.core.workflows.core_steps.sinks.roboflow.model_monitoring_inference_aggregator.v1 import (
ModuleNotFoundError: No module named 'inference.core.workflows.core_steps.sinks.roboflow.model_monitoring_inference_aggregator'
```

<img width="1728" alt="Screenshot 2024-11-24 at 14 37 41" src="https://github.com/user-attachments/assets/321a4345-600f-4759-aaf5-0b55a1d60c5e">

If I download the source code from the latest release the files are present so I'm not sure what would be causing it.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by PawelPeczek-Roboflow** [comment]
Thanks for reporting, this should fix the problem: https://github.com/roboflow/inference/pull/830
I am cutting release to propagate the fix

**Comment by PawelPeczek-Roboflow** [comment]
We have cut a release, should work now under `0.28.1`, version `0.28.0` got junked in pypi
